### ISSUE TITLE
Add Test coverage tracking

### ISSUE THREAD

**Issue by apolishch** [apolishch/dreamteam#12]
- [x] Pick a tool (SimpleCov is popular)
- [x] Integrate tool with CD pipeline
- [ ] Set bar high (90% seems fair)
